services:

  postgres:
    container_name: pro_fugi_backend_postgres
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_HOST_PORT}:${DB_CONTAINER_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    container_name: pro_fugi_backend_redis
    image: redis:7
    restart: unless-stopped
    ports:
      - '${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}'
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --port ${REDIS_CONTAINER_PORT}
    volumes:
      - redis_data:/data

  app:
    container_name: pro_fugi_backend_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '${APP_HOST_PORT}:${APP_CONTAINER_PORT}'
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
